In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
x = np.array([2,5,7,6,3,7,5])
print(x)
print('Total Elements -> ',x.size)
print('Dimension wise Element -> ',x.shape)
print('Dimension Count -> ',x.ndim)

[2 5 7 6 3 7 5]
Total Elements ->  7
Dimension wise Element ->  (7,)
Dimension Count ->  1


In [4]:
y = np.array([[3,2,4],[7,5,6]])
print(y)
print('Total Elements -> ',y.size)
print('Dimension wise Element -> ',y.shape)
print('Dimension Count -> ',y.ndim)

[[3 2 4]
 [7 5 6]]
Total Elements ->  6
Dimension wise Element ->  (2, 3)
Dimension Count ->  2


In [5]:
z = np.array([[3,2,4],[7,5,6],[8,6,3]])
print(z)
print('Total Elements -> ',z.size)
print('Dimension wise Element -> ',z.shape)
print('Dimension Count -> ',z.ndim)

[[3 2 4]
 [7 5 6]
 [8 6 3]]
Total Elements ->  9
Dimension wise Element ->  (3, 3)
Dimension Count ->  2


In [6]:
x = [1,2,3,4,5]
z = np.array([[x,x,x],[x,x,x],[x,x,x]])
print('shape - ',z.shape)
print(z)

shape -  (3, 3, 5)
[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


In [9]:
x = [1,2,3,4,5,6]
z = np.array([[x,x,x,x,x],[x,x,x,x,x],[x,x,x,x,x],[x,x,x,x,x],[x,x,x,x,x]])
print(z.shape)

(5, 5, 6)


In [10]:
np.arange(0,10,.5)                #np.arange(start,ending,change)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [11]:
d = np.arange(-10,11,0.5)
d.shape

(42,)

In [12]:
d.reshape(6,7)                 #reshape(rows,colum)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [13]:
d.reshape(2,3,7)       #from above 6 can be written as 2*3 or 3*2.....therefore(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [17]:
a = np.linspace(1, 1000 , 11)         #(start,end, no. of items)      divide equally
a 

array([   1. ,  100.9,  200.8,  300.7,  400.6,  500.5,  600.4,  700.3,
        800.2,  900.1, 1000. ])

In [18]:
np.random.randint(1,5,(10,10))     #(start,end,(a x b))      a x b matrix      from start to (end - 1)

array([[1, 1, 3, 3, 2, 4, 3, 2, 4, 3],
       [3, 4, 2, 2, 2, 4, 4, 2, 4, 1],
       [1, 4, 1, 3, 2, 1, 4, 2, 3, 4],
       [3, 4, 1, 2, 3, 1, 3, 1, 3, 4],
       [3, 1, 1, 1, 2, 2, 1, 1, 3, 1],
       [4, 4, 1, 3, 1, 1, 1, 1, 1, 2],
       [1, 4, 4, 3, 3, 2, 1, 1, 2, 4],
       [1, 3, 2, 2, 2, 1, 3, 3, 3, 2],
       [1, 4, 4, 2, 4, 3, 4, 2, 3, 3],
       [3, 4, 3, 3, 3, 3, 3, 4, 2, 1]])

In [20]:
d = np.random.randint(1,6,(10,10))
d

array([[2, 1, 1, 1, 2, 2, 2, 2, 3, 5],
       [5, 4, 2, 4, 5, 5, 3, 5, 1, 5],
       [5, 1, 2, 2, 4, 2, 1, 4, 3, 5],
       [2, 1, 3, 3, 3, 4, 5, 5, 2, 2],
       [4, 1, 5, 3, 5, 3, 3, 4, 5, 3],
       [2, 1, 4, 1, 4, 3, 1, 2, 4, 1],
       [1, 4, 3, 2, 3, 2, 4, 4, 3, 3],
       [1, 2, 3, 2, 3, 2, 2, 2, 2, 5],
       [4, 3, 5, 4, 2, 5, 3, 5, 4, 4],
       [1, 5, 4, 5, 4, 3, 5, 2, 2, 2]])

In [21]:
d[-1]

array([1, 5, 4, 5, 4, 3, 5, 2, 2, 2])

In [24]:
d[0,0]             #d[0][0]


2

In [25]:
d[3,5]

4

In [26]:
d[:,0]                 #all rows of index 0

array([2, 5, 5, 2, 4, 2, 1, 1, 4, 1])

In [27]:
d[:,-3]

array([2, 5, 4, 5, 4, 2, 4, 2, 5, 2])

In [28]:
d[:5,2]                  #first five rows of column index 2

array([1, 2, 2, 3, 5])

In [29]:
d[:5, :5]           #first 5 rows first 5 column

array([[2, 1, 1, 1, 2],
       [5, 4, 2, 4, 5],
       [5, 1, 2, 2, 4],
       [2, 1, 3, 3, 3],
       [4, 1, 5, 3, 5]])

In [30]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x ,'\n', y)

[[6 7 5]
 [5 1 7]
 [4 9 9]] 
 [[1 7 9]
 [6 8 2]
 [4 1 2]]


In [31]:
x + y

array([[ 7, 14, 14],
       [11,  9,  9],
       [ 8, 10, 11]])

In [32]:
x - y

array([[ 5,  0, -4],
       [-1, -7,  5],
       [ 0,  8,  7]])

In [33]:
x * y

array([[ 6, 49, 45],
       [30,  8, 14],
       [16,  9, 18]])

In [35]:
x / y

array([[6.        , 1.        , 0.55555556],
       [0.83333333, 0.125     , 3.5       ],
       [1.        , 9.        , 4.5       ]])

In [36]:
x + 10

array([[16, 17, 15],
       [15, 11, 17],
       [14, 19, 19]])

In [37]:
x * 10

array([[60, 70, 50],
       [50, 10, 70],
       [40, 90, 90]])

In [38]:
np.dot(x,y)                     #dot product

array([[ 68, 103,  78],
       [ 39,  50,  61],
       [ 94, 109,  72]])

In [39]:
np.matmul(x,y)                   #matrix multiplication

array([[ 68, 103,  78],
       [ 39,  50,  61],
       [ 94, 109,  72]])

In [40]:
np.multiply(x,y)

array([[ 6, 49, 45],
       [30,  8, 14],
       [16,  9, 18]])

In [41]:
np.cross(x,y)                 #cross product

array([[ 28, -49,  35],
       [-54,  32,  34],
       [  9,  28, -32]])

In [42]:
np.hstack([x,y])                  #horizontal stacking

array([[6, 7, 5, 1, 7, 9],
       [5, 1, 7, 6, 8, 2],
       [4, 9, 9, 4, 1, 2]])

In [43]:
np.vstack([x,y])               #vertical stacking

array([[6, 7, 5],
       [5, 1, 7],
       [4, 9, 9],
       [1, 7, 9],
       [6, 8, 2],
       [4, 1, 2]])

In [46]:
np.append(x , y , axis = 1)                #axix -> row wise or column wise

array([[6, 7, 5, 1, 7, 9],
       [5, 1, 7, 6, 8, 2],
       [4, 9, 9, 4, 1, 2]])

In [47]:
x.max()

9

In [48]:
x.max(axis = 0)

array([6, 9, 9])

In [50]:
x.min(axis = 1)

array([5, 1, 4])

In [51]:
x.flatten()                       #change any dimension to 1D

array([6, 7, 5, 5, 1, 7, 4, 9, 9])

In [52]:
d[d > 3]                            #boolean filter

array([5, 5, 4, 4, 5, 5, 5, 5, 5, 4, 4, 5, 4, 5, 5, 4, 5, 5, 4, 5, 4, 4,
       4, 4, 4, 4, 5, 4, 5, 4, 5, 5, 4, 4, 5, 4, 5, 4, 5])

In [53]:
d[d == 1]            #give all the ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])